version: "3.9"

services:

  dev_postgres:
    container_name: "dev_postgres"
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  dev_solr_initializer:
    container_name: "dev_solr_initializer"
    image: alpine
    restart: "no"
    entrypoint: |
      /bin/sh -c "chown 8983:8983 /conf"
    volumes:
      - ./solr/conf:/conf

  dev_solr:
    container_name: "dev_solr"
    image: solr:8.11.1
    depends_on:
      - dev_solr_initializer
    restart: on-failure
    ports:
      - "8983:8983"
    entrypoint: |
      bash -c "chown -R 8983:8983 /var/solr && cd /opt/solr-8.11.1/server/solr/configsets/_default/conf && cp -R -n . /opt/solr-8.11.1/server/solr/collection1 && solr-create -c collection1 -d /opt/solr-8.11.1/server/solr/collection1"
    volumes:
      - ./solr/data:/var/solr
      - ./solr/conf:/opt/solr-8.11.1/server/solr/collection1

  dev_smtp:
    container_name: "dev_smtp"
    image: maildev/maildev:2.0.5
    restart: on-failure
    ports:
      - "25:1025" # smtp server
      - "1080:1080" # web ui
    volumes:
      - ./smtp/data:/tmp/maildev-1
